version: '3'
services:
  frontend:
    build: .
    command: bash -c "yarn install && npm start"
    working_dir: /app
    stdin_open: true
    volumes:
      - '.:/app'
      - /app/node_modules
    expose:
      - "8080"
    ports:
      - '8080:8080'
    networks:
      - product-manager

networks:
  product-manager:
    driver: bridge
