default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: b182082b66ce24
  password: f84ed5b8

development:
  <<: *default
  ssl_mode: disabled
  url: mysql2://b182082b66ce24:f84ed5b8@us-cdbr-east-02.cleardb.com/heroku_1b1ee060ffbbd5a?reconnect=true


test:
  <<: *default
  database: app_name_test

production:
  <<: *default
  database: app_name_production
  username: app_name
  password: <%= ENV['APP_NAME_DATABASE_PASSWORD'] %>
