version: '3'
services:
  backend:
    build:
      context: ./backend
    working_dir: /app
    command: bash -c "bundle install && bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p 3000"
    volumes:
      - './backend:/app'
    expose:
      - "3000"
    ports:
      - '3000:3000'
    networks:
      - product-manager

  frontend:
    build:
      context: ./frontend
    command: bash -c "yarn install && npm start"
    working_dir: /app
    stdin_open: true
    volumes:
      - './frontend:/app'
      - /app/node_modules
    expose:
      - "8080"
    ports:
      - '8080:8080'
    networks:
      - product-manager
    depends_on:
      - backend

networks:
  product-manager:
    driver: bridge
